# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZLddThOqWxJkdrHzF-aSXk3Sw3XoBg
"""

# app.py
# Contestable AI Interface MVP for Norm Hardy Prize-style submission
# Run with: streamlit run app.py

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime

st.set_page_config(
    page_title="Contestable AI Decision Interface",
    page_icon="🛡️",
    layout="wide"
)

# -----------------------------
# Basic styling
# -----------------------------
st.markdown("""
<style>
.main-title {
    font-size: 2.2rem;
    font-weight: 800;
    margin-bottom: 0.2rem;
}
.subtitle {
    color: #555;
    font-size: 1.05rem;
    margin-bottom: 1.5rem;
}
.card {
    padding: 1.1rem;
    border-radius: 14px;
    border: 1px solid #e5e7eb;
    background-color: #ffffff;
    box-shadow: 0 1px 4px rgba(0,0,0,0.04);
    margin-bottom: 1rem;
}
.good {
    padding: 0.6rem 0.8rem;
    border-radius: 10px;
    background-color: #ecfdf5;
    border: 1px solid #a7f3d0;
}
.warn {
    padding: 0.6rem 0.8rem;
    border-radius: 10px;
    background-color: #fffbeb;
    border: 1px solid #fde68a;
}
.bad {
    padding: 0.6rem 0.8rem;
    border-radius: 10px;
    background-color: #fef2f2;
    border: 1px solid #fecaca;
}
.small-note {
    font-size: 0.88rem;
    color: #666;
}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# Demo decision engine
# -----------------------------
def compute_decision(income, debt_ratio, employment_years, missing_docs, credit_history, vulnerable_context):
    """
    Simulated AI decision model.
    This is intentionally transparent for MVP demonstration.
    Replace with a real model later if needed.
    """
    score = 50
    score += min(income / 2000, 20)
    score -= debt_ratio * 35
    score += min(employment_years * 3, 15)
    score += credit_history * 1.5
    score -= missing_docs * 8

    if vulnerable_context:
        # Not a positive decision factor; it only triggers extra review safeguard.
        score += 0

    score = max(0, min(100, score))

    if score >= 70:
        decision = "Approved"
        decision_class = "good"
    elif score >= 55:
        decision = "Conditional Review"
        decision_class = "warn"
    else:
        decision = "Rejected"
        decision_class = "bad"

    uncertainty = 100 - abs(score - 55) * 1.5
    uncertainty = max(15, min(85, uncertainty))

    if missing_docs >= 2 or vulnerable_context or uncertainty >= 65:
        review_recommended = True
    else:
        review_recommended = False

    factors = {
        "Income stability": min(income / 2000, 20),
        "Debt burden": -debt_ratio * 35,
        "Employment history": min(employment_years * 3, 15),
        "Credit history": credit_history * 1.5,
        "Missing documents": -missing_docs * 8,
    }

    return score, decision, decision_class, uncertainty, review_recommended, factors


def plain_language_factor(name, value):
    if name == "Income stability":
        return "Higher income improved the decision score." if value >= 10 else "Income level gave limited support to the application."
    if name == "Debt burden":
        return "Debt burden reduced the score." if value < -10 else "Debt burden had limited negative effect."
    if name == "Employment history":
        return "Longer employment history supported the application." if value >= 6 else "Employment history was not strong enough to support the decision much."
    if name == "Credit history":
        return "Credit history supported the application." if value >= 8 else "Credit history gave only moderate support."
    if name == "Missing documents":
        return "Missing documents reduced confidence in the decision." if value < 0 else "No missing documents affected the decision."
    return "This factor influenced the decision."


# -----------------------------
# Session state
# -----------------------------
if "case_submitted" not in st.session_state:
    st.session_state.case_submitted = False
if "appeal_submitted" not in st.session_state:
    st.session_state.appeal_submitted = False
if "audit_log" not in st.session_state:
    st.session_state.audit_log = []

# -----------------------------
# Header
# -----------------------------
st.markdown('<div class="main-title">🛡️ Contestable AI Decision Interface</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">A working MVP showing how explainability can become guided, secure, and actionable contestability.</div>',
    unsafe_allow_html=True
)

with st.expander("What this MVP demonstrates", expanded=False):
    st.write(
        """
        This prototype demonstrates an interaction design where users do not merely receive an AI decision.
        They can understand the decision, see uncertainty, identify possible errors, submit structured evidence,
        and request human review. The goal is to make the safer and fairer path easier than a vague appeal process.
        """
    )

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("Demo Scenario")
scenario = st.sidebar.selectbox(
    "Choose decision context",
    ["Loan application", "Hiring shortlisting", "Insurance claim", "University admission"]
)

st.sidebar.markdown("---")
st.sidebar.caption("This MVP uses a simulated decision model for demonstration.")

# -----------------------------
# Main input form
# -----------------------------
left, right = st.columns([1, 1])

with left:
    st.markdown("### 1. Application Data")
    with st.form("application_form"):
        income = st.slider("Monthly income / capacity indicator", 500, 10000, 2600, step=100)
        debt_ratio = st.slider("Debt or burden ratio", 0.0, 1.0, 0.42, step=0.01)
        employment_years = st.slider("Years of stable employment / activity", 0, 15, 2)
        missing_docs = st.slider("Missing or unclear documents", 0, 5, 2)
        credit_history = st.slider("Relevant history score", 0, 10, 5)
        vulnerable_context = st.checkbox("Context may require careful human review", value=True)
        submitted = st.form_submit_button("Run decision")

    if submitted:
        st.session_state.case_submitted = True
        st.session_state.appeal_submitted = False
        st.session_state.audit_log.append({
            "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "event": "AI decision generated",
            "scenario": scenario
        })

with right:
    st.markdown("### 2. Decision Summary")

    if st.session_state.case_submitted:
        score, decision, decision_class, uncertainty, review_recommended, factors = compute_decision(
            income, debt_ratio, employment_years, missing_docs, credit_history, vulnerable_context
        )

        st.markdown(f"<div class='{decision_class}'><b>Decision:</b> {decision}<br><b>Decision score:</b> {score:.1f}/100</div>", unsafe_allow_html=True)
        st.progress(int(score))

        st.markdown("#### Uncertainty")
        st.progress(int(uncertainty))
        st.write(f"Estimated uncertainty: **{uncertainty:.1f}%**")

        if review_recommended:
            st.markdown("<div class='warn'><b>Human review recommended.</b><br>This decision involves uncertainty, missing information, or sensitive context.</div>", unsafe_allow_html=True)
        else:
            st.markdown("<div class='good'><b>No automatic review trigger.</b><br>The user can still contest the decision.</div>", unsafe_allow_html=True)
    else:
        st.info("Submit the application data to generate a decision.")

# -----------------------------
# Explanation and contestability
# -----------------------------
if st.session_state.case_submitted:
    st.markdown("---")
    st.markdown("### 3. Human-Readable Explanation")

    score, decision, decision_class, uncertainty, review_recommended, factors = compute_decision(
        income, debt_ratio, employment_years, missing_docs, credit_history, vulnerable_context
    )

    factor_df = pd.DataFrame({
        "Factor": list(factors.keys()),
        "Influence": list(factors.values()),
        "Plain-language meaning": [plain_language_factor(k, v) for k, v in factors.items()]
    }).sort_values("Influence", ascending=True)

    col_a, col_b = st.columns([1, 1])

    with col_a:
        st.dataframe(factor_df, use_container_width=True, hide_index=True)

    with col_b:
        st.bar_chart(factor_df.set_index("Factor")["Influence"])

    st.markdown("### 4. Guided Contestability Workflow")
    st.write("Instead of a vague appeal button, the user is guided to contest specific parts of the decision.")

    with st.form("contest_form"):
        reasons = st.multiselect(
            "What do you want to challenge?",
            [
                "Incorrect data was used",
                "Important document or evidence is missing",
                "The model misunderstood my context",
                "The decision may be unfair or biased",
                "The decision is too uncertain for automatic processing",
                "I want a human reviewer to inspect this case"
            ],
            default=["Important document or evidence is missing", "I want a human reviewer to inspect this case"]
        )

        explanation = st.text_area(
            "Explain your challenge in your own words",
            placeholder="Example: My employment document was not included. My current income is also higher than shown."
        )

        uploaded = st.file_uploader("Optional: upload supporting evidence", type=["pdf", "png", "jpg", "jpeg", "docx"])

        review_type = st.radio(
            "Choose review path",
            [
                "Fast human review",
                "Full appeal review",
                "Correct data and rerun decision",
                "Request explanation only"
            ]
        )

        consent = st.checkbox(
            "I consent to share only the selected information with the reviewer for this specific purpose.",
            value=False
        )

        contest_submitted = st.form_submit_button("Submit contestation request")

    if contest_submitted:
        if not consent:
            st.error("Please give purpose-limited consent before submitting the contestation request.")
        elif not reasons:
            st.error("Please select at least one reason for contesting the decision.")
        else:
            st.session_state.appeal_submitted = True
            st.session_state.audit_log.append({
                "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "event": "Contestation request submitted",
                "scenario": scenario,
                "review_type": review_type
            })
            st.success("Contestation request submitted. A human reviewer will receive the selected information only for this review purpose.")

    if st.session_state.appeal_submitted:
        st.markdown("### 5. Contestation Receipt")
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.write(f"**Scenario:** {scenario}")
        st.write(f"**Original decision:** {decision}")
        st.write(f"**Review path:** {review_type}")
        st.write("**Submitted reasons:**")
        for r in reasons:
            st.write(f"- {r}")
        if explanation:
            st.write("**User explanation:**")
            st.write(explanation)
        if uploaded is not None:
            st.write(f"**Evidence uploaded:** {uploaded.name}")
        st.write("**Purpose limitation:** Reviewer may use submitted information only to evaluate this contestation request.")
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("### 6. Audit Trail")
    if st.session_state.audit_log:
        st.dataframe(pd.DataFrame(st.session_state.audit_log), use_container_width=True, hide_index=True)
    else:
        st.info("No audit events yet.")

# -----------------------------
# Research framing section
# -----------------------------
st.markdown("---")
st.markdown("### Research Contribution")
st.write(
    """
    This MVP operationalizes the idea that explainability alone is insufficient. A user should be able to move from
    explanation to safe action: correcting data, submitting evidence, requesting human review, and limiting how their
    information is used. This turns passive transparency into actionable contestability.
    """
)

st.markdown("### Suggested Evaluation")
st.write(
    """
    For a small user study, compare this prototype with a standard AI rejection notice. Measure whether users can:
    understand the decision, identify possible errors, choose the correct review path, feel procedurally protected,
    and avoid oversharing unnecessary personal data.
    """
)